//Hue Anh Huynh
//1/25/17
//Ch. 3 Exercises


#include <iostream>
#include<math.h>


using namespace std;

int main()
{
//price of tickets
    int a = 15;
    int b = 12;
    int c = 9;
//# of tickets sold
    int aNum, bNum, cNum;
    int income;

    cout << "This program will calculate the amount of income generated by the tickets at a stadium.\n";
    cout << "Enter the amount of Class A tickets sold: ";
    cin >> aNum;
    cout << "Enter the amount of Class B tickets sold: ";
    cin >> bNum;
    cout << "Enter the amount of Class C tickets sold: ";
    cin >> cNum;

    income = (a * aNum) + (b * bNum) + (c * cNum);

    cout << "The amount of income generated from ticket sales: $" << income << endl << endl;



    return 0;
}
